// INFORMACIÓN DE LOS DOCTORES
const doctoresInfo = [
  /* 1er Piso */
  {
    id: 1,
    nombre: "Dra. María Elena Muñoz May",
    especialidad: "Ginecología, obstreticia",
    piso: "1er. Piso",
    extension: "2200",
  },

  {
    id: 2,
    nombre: "Dra. Ramona García Cordova",
    especialidad: "Ginecología, perinatología",
    piso: "1er. Piso",
    extension: "2200",
  },
  {
    id: 3,
    nombre: "Dr. Andrés González Montero",
    especialidad: "Medicina interna",
    piso: "1er. Piso",
    extension: "2200",
  },
  {
    id: 4,
    nombre: "Dra. Lidia Reyes Mena",
    especialidad: "Odontología",
    piso: "1er. Piso",
    extension: "2200",
  },
  {
    id: 5,
    nombre: "Dr. Francisco Alvarado Alemán",
    especialidad: "Pediatra Infectólogo",
    piso: "1er. Piso",
    extension: "2200",
  },
  {
    id: 6,
    nombre: "Dra. Elizabeth Solano Pareja",
    especialidad: "Pediatría",
    piso: "1er. Piso",
    extension: "2200",
  },
  {
    id: 7,
    nombre: "Dr. Pedro García Limón",
    especialidad: "Traumatología, ortopedia",
    piso: "1er. Piso",
    extension: "2200",
  },
  {
    id: 8,
    nombre: "Dr. Alejandro Solís Oliveres",
    especialidad: "Traumatologia, Medicina del deporte",
    piso: "1er. Piso",
    extension: "2200",
  },
  /* 2do. Piso sala A */
  {
    id: 9,
    nombre: "Dr. Miguel Ángel Echeverria",
    especialidad: "Cardiología, medicina interna",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 10,
    nombre: "Dr. Edgar Benitez Cejudo",
    especialidad: "Cirugía general, laparoscopía, cirugía de trasplante renal",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 11,
    nombre: "Dr. Oscar Infante",
    especialidad: "Cirugía pediátrica",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 12,
    nombre: "Dr. Christian Tejeda",
    especialidad: "Ginecología, obstetricia",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 13,
    nombre: "Dr. Miguel Angel Blancas",
    especialidad: "Ginecología, obstetricia",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 14,
    nombre: "Dra. Mariana García Elías",
    especialidad: "Ginecología, obstetricia, cirugía de mínima invasión",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 15,
    nombre: "Dr. Rodolfo Anzures Medina",
    especialidad: "Oftalmología",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 16,
    nombre: "Dr. Gabriel Carrasco Barrera",
    especialidad: "Otorrinolaringología",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 17,
    nombre: "Dra. Nidia Gallardo Ibáñez",
    especialidad: "Otorrinolaringología",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 18,
    nombre: "Dr. Benjamin Estrada",
    especialidad: "Traumatología, ortopedia",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 19,
    nombre: "Dr. Luis Manuel Cano Sosa",
    especialidad: "Cardiologia",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 20,
    nombre: "Dr. Begoña Lepe Anasagasti",
    especialidad: "Internista",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 21,
    nombre: "Dra. Olga Luna",
    especialidad: "Traumatología, ortopedia",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 22,
    nombre: "Dr. Carlos Calderón Muñoz",
    especialidad: "Urología",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 23,
    nombre: "Dr. Cristian Alejandro Aguirre",
    especialidad: "Gastroenterologia",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 24,
    nombre: "Dra. Erika Luna Gómez",
    especialidad: "Pediatría",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 25,
    nombre: "Lic. Michelle Gamboa",
    especialidad: "Nutriologa",
    piso: "2do. Piso sala A",
    extension: "2300",
  },
  {
    id: 26,
    nombre: "Dra. Daliana Mendoza Martínez",
    especialidad: "Cirugía general, laparoscopía",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 27,
    nombre: "Dr. Gustavo Segovia Cuevas",
    especialidad: "Cirugía general, laparoscopía, endoscopia, gastro-cirugía",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 28,
    nombre: "Dr. Ricardo Cabrilla Torres",
    especialidad: "Cirugía pediátrica, laparoscópica",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 29,
    nombre: "Dra. Tania Canseco",
    especialidad: "Geriatría",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 30,
    nombre: "Dr. Pedro Chable Del Ángel",
    especialidad: "Ginecología",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 31,
    nombre: "Dr. Jorge Cabral Calvillo",
    especialidad: "Ginecología, obstetricia",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 32,
    nombre: "Dr. Joel Madera Gamboa",
    especialidad: "Ginecología, perinatología",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 33,
    nombre: "Dr. Josué Molina Ruíz",
    especialidad: "Nefrología",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 34,
    nombre: "Dra. Jesica Avila",
    especialidad: "Neurología",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 35,
    nombre: "Dr. Julio Felipe Vega",
    especialidad: "Otorrinolaringología",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 36,
    nombre: "Dr. Zamir Luna Ramos",
    especialidad: "Traumatología, ortopedia",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
  {
    id: 37,
    nombre: "Dr. Jose de Jesus Fuentes Quezada",
    especialidad: "Angioligia",
    piso: "2do. Piso sala B",
    extension: "2400",
  },
];
