// INFORMACIÓN DE LOS DOCTORES
const doctoresInfo = [
  {
    id: 1,
    nombre: "Dra. Maria Elena Muñoz May",
    especialidad: "Ginecología & obstreticia",
    telefono: "999 999 9999",
  },

  {
    id: 2,
    nombre: "Dra. Ramona García Cordova",
    especialidad: "Ginecología & perinatología",
    telefono: "999 999 9999",
  },
  {
    id: 3,
    nombre: "Dr. Andrés González Montero",
    especialidad: "Medicina interna",
    telefono: "999 999 9999",
  },
  {
    id: 4,
    nombre: "Dr. Alejandro Solís Oliveres",
    especialidad: "Medicina del deporte",
    telefono: "999 999 9999",
  },
  {
    id: 5,
    nombre: "Dr. Miguel Ángel Echeverria",
    especialidad: "Cardiología & medicina interna",
    telefono: "999 999 9999",
  },
  {
    id: 6,
    nombre: "Dr. Armando Amador",
    especialidad: "Cirugía general & laparoscopía",
    telefono: "999 999 9999",
  },
  {
    id: 7,
    nombre: "Dr. Edgar Benitez Cejudo",
    especialidad: "Cirugía general, laparoscopía & cirugía de trasplante renal",
    telefono: "999 999 9999",
  },
  {
    id: 8,
    nombre: "Dr. Oscar Infante",
    especialidad: "Cirugía pediátrica",
    telefono: "999 999 9999",
  },
  {
    id: 9,
    nombre: "Dr. Miguel Castro Cervantes",
    especialidad: "Cirujano oncólogo",
    telefono: "999 999 9999",
  },
  {
    id: 10,
    nombre: "Dr. Christian Tejeda",
    especialidad: "Ginecología & obstetricia",
    telefono: "999 999 9999",
  },
  {
    id: 11,
    nombre: "Dr. Miguel Angel Blancas",
    especialidad: "Ginecología & obstetricia",
    telefono: "999 999 9999",
  },
  {
    id: 12,
    nombre: "Dra. Mariana García Elías",
    especialidad: "Ginecología, obstetricia & cirugía de mínima invasión",
    telefono: "999 999 9999",
  },
  {
    id: 13,
    nombre: "Dr. Rodolfo Anzures",
    especialidad: "Oftalmología",
    telefono: "999 999 9999",
  },
  {
    id: 14,
    nombre: "Dr. Gabriel Carrasco Barrera",
    especialidad: "Otorrinolaringología",
    telefono: "999 999 9999",
  },
  {
    id: 15,
    nombre: "Dra. Nidia Gallardo Ibáñez",
    especialidad: "Otorrinolaringología",
    telefono: "999 999 9999",
  },
  {
    id: 16,
    nombre: "Dr. Marco Antonio Segovia",
    especialidad: "Pediatra alergólogo",
    telefono: "999 999 9999",
  },
  {
    id: 17,
    nombre: "Dra. Olga Luna",
    especialidad: "Traumatología & ortopedia",
    telefono: "999 999 9999",
  },
  {
    id: 18,
    nombre: "Dr. Carlos Calderón Muñoz",
    especialidad: "Urología",
    telefono: "999 999 9999",
  },
  {
    id: 19,
    nombre: "Dra. Daliana Mendoza Martínez",
    especialidad: "Cirugía general & laparoscopía",
    telefono: "999 999 9999",
  },
  {
    id: 20,
    nombre: "Dr. Gustavo Segovia",
    especialidad: "Cirugía general, laparoscopía, endoscopia & gastro-cirugía",
    telefono: "999 999 9999",
  },
  {
    id: 21,
    nombre: "Dr. Ricardo Cabrilla Torres",
    especialidad: "Cirugía pediátrica & laparoscópica",
    telefono: "999 999 9999",
  },
  {
    id: 22,
    nombre: "Dra. Tania Canseco",
    especialidad: "Geriatría",
    telefono: "999 999 9999",
  },
  {
    id: 23,
    nombre: "Dr. Pedro Chable Del Ángel",
    especialidad: "Ginecología",
    telefono: "999 999 9999",
  },
  {
    id: 24,
    nombre: "Dr. Danny Martínez Alanis",
    especialidad: "Ginecología oncológica",
    telefono: "999 999 9999",
  },
  {
    id: 25,
    nombre: "Dr. Jorge Cabral Calvillo",
    especialidad: "Ginecología & obstetricia",
    telefono: "999 999 9999",
  },
  {
    id: 26,
    nombre: "Dr. Joel Madera Gamboa",
    especialidad: "Ginecología & perinatología",
    telefono: "999 999 9999",
  },
  {
    id: 27,
    nombre: "Dra. Lizbeth Campos Villa",
    especialidad: "Ginecología, obstetricia, colposcopista & cirugía",
    telefono: "999 999 9999",
  },
  {
    id: 28,
    nombre: "Dr. Josué Molina Ruíz",
    especialidad: "Nefrología",
    telefono: "999 999 9999",
  },
  {
    id: 29,
    nombre: "Dra. Jesica Avila",
    especialidad: "Neurología",
    telefono: "999 999 9999",
  },
  {
    id: 30,
    nombre: "Dr. Julio Felipe Vega",
    especialidad: "Otorrinolaringología",
    telefono: "999 999 9999",
  },
  {
    id: 31,
    nombre: "Dra. Erika Luna Gómez",
    especialidad: "Pediatría",
    telefono: "999 999 9999",
  },
  {
    id: 32,
    nombre: "Dr. Zamir Luna Ramos",
    especialidad: "Traumatología & ortopedia",
    telefono: "999 999 9999",
  },
];
